### ISSUE TITLE
Registrar usuario desde cualquier página

### ISSUE THREAD

**Issue by btkramm** [UC-IIC2513-2016-2/syllabus#1]
He buscado unas cuantas horas cómo conseguir que un usuario pueda registrarse desde cualquier página, en particular desde `home`, pero todos proponen diversas soluciones y ninguna la entiendo del todo.

Por como lo estoy intentando el primer error que obtengo es `No route matches [POST] "/"` lo cual es natural porque intento hacer POST estando en la raíz de la aplicación.

Estoy utilizando el helper `form_for` indicando al modelo @user. Necesito una solución tal que sea capaz de guardar una instancia del modelo User en @user antes de hacer submit, porque sino el helper reclama que le he entregado un valor nulo.

Ayuda por favor, creo que solucionando estoy aprendería bastante :).

**Comment by lfpose** [comment]
Y si pruebas entregando un nuevo modelo `@user = User.new` como parámetro del form?

**Comment by btkramm** [comment]
Es una de las soluciones que rondan, pero desconozco cuales son las mejores prácticas, así que no he decidido si usarla o no aún.

**Comment by raulmt** [comment]
Lo que @lfpose te propone es, de hecho, como se hace en un scaffold de cualquier modelo. El helper `form_for`, si no le especificas una URL explícitamente, intentará deducir una desde el objeto principal que le entregas. Si el el objeto es de la clase `User`, por ejemplo, supondrá que el path para enviar el formulario es ya sea un POST a /users o un PATCH a /users/:id, dependiendo de si es un objeto nuevo o existente. En el caso de lo que te propone @lfpose, sería un objeto nuevo y, por tanto, el primer path que menciono.

Aunque buscar soluciones en la web es una gran ayuda, te recomiendo también siempre leer la documentación de lo que estés usando. Puede que la solución esté ahí mismo o, por lo menos, te ayudará a entender bien por qué la solución que encontraste funciona. Aquí está la [guía sobre formularios de Rails](http://guides.rubyonrails.org/form_helpers.html), y la [documentación específica de form_for](http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_for) (en particular, la sección "Resource-oriented style").

Finalmente, ¡enhorabuena! te has ganado la medalla "primer post en el foro del curso".

![my_medal](https://cloud.githubusercontent.com/assets/632782/19024497/5ab36f2c-88db-11e6-91bb-31df76961a10.jpg)

Por favor recuerda cerrar el issue si se resolvió tu duda.

**Comment by btkramm** [comment]
Sí, funciona. Efectivamente no solo rondé en internet variado sino que también mucho en la documentación pero todavía no entiendo lo suficiente como para moverme con fluidez en ella.

Para que funcionase añadir en mis rutas `post '/', to: 'user#create'`  y en form_to `User.new`. Aún así me parece extraño lo que agregué en rutas ¿Fue correcto? Digo que me parece extraño porque es información que form_to ya posee y además ¿Qué hago si en un futuro coloco otro botón en mi home que también hace post?

**Comment by raulmt** [comment]
No, @btkramm , lo que hiciste no fue lo más correcto, aún cuando funcione. Si lo que quieres es crear un recurso "User", eso debiera ocurrir con un POST a /users, que es la ruta que te crea el incluir `resources :users` en tu archivo routes.rb.

Creo que ya no tengo claro exactamente qué es lo que quieres lograr.

P: ¿Quieres tener un formulario de registro en todas las páginas?
R: Aunque sería extraño, pero para lo único que necesitas es que el formulario que incluyas en todas las páginas se envíe a la ruta correcta. Un `<%= form_for @new_user do |f| %>` con `@new_user` siendo una instancia nueva del modelo `User`, por default, generará que el formulario apunte al POST /users que te mencioné más arriba.

P: ¿Quieres tener un link a la página de registro en todas tus páginas?
R: Si sigues las rutas _resource oriented_, tendrías una ruta /users/new para la página del formulario de registro, y además tendrías el helper de ruta `new_users_path`, por lo que sólo tendrías que generar un link utilizando ese route helper, y el formulario sería igual a lo anterior.

¿Quizá te referías a otra cosa?

**Comment by btkramm** [comment]
La idea es que en el home exista la posibilidad de registrarse, pero no confundir con poder apretar un botón que te lleva a un formulario, sino que el formulario está explícito en el mismo home.

El problema que tengo con el punto 1 es que no sé como hacer que @new_user exista, porque el formulario ya fue creado y nunca se ejecutó el método `new` del modelo `User`. Según tengo entendido el ciclo de vida para un formulario común y corriente es crear `@user` en `new` para luego mostrar `new.html.erb` con el formulario, el cliente rellena y al hacer submit se llama a `create`. Entonces, si dejo el formulario en home, cuando creo a `@user` ¿?

**Comment by raulmt** [comment]
Ahh, creo que ahora entiendo tu problema.

Esencialmente, tus templates siempre van a necesitar de ciertos datos expuestos ya sea como variables de instancia o, en el caso de los partials, como [variables locales](http://guides.rubyonrails.org/layouts_and_rendering.html#using-partials). Así que para poder _renderearlos_ necesitarás que esas variables estén disponibles. Y los únicos lugares desde donde puedes asignar esas variables son desde el controller en el caso de variables de instancia o también desde otros templates en el caso de partials (aunque en este segundo caso, probablemente igual necesitarás alguna variable de instancia para el template principal…). Así que si vas a usar un template directamente o indirectamente como partial dentro de otro template, en cualquier caso necesitarás asignar ciertas variables de instancia desde la acción que gatilla el rendering.

Sí, esto implica que probablemente tengas que asignar las mismas variables de instancia desde dos acciones diferentes si es que quieres usar X partial desde esas dos acciones diferentes. En este caso lo repetido no es mucho… sería un `@new_user = User.new`, cierto? Si es que fueran muchas variables de instancia las que necesitas o un código muy complejo que no quieres repetir, entonces lo que te queda es usar Ruby para seguir DRY (don't repeat yourself): puedes crear un módulo que incluyes como mixin en ambos controllers, y así tus dos acciones sólo llaman a ese método del módulo (por ejemplo).

Con la línea `@new_user = User.new` en el action del home y en el action user#new, podrás usar el mismo template en ambos lados.

Creo que uno tiende a pensar en "formulario para registro de usuario" como una unidad de lógica + vista, que pueda ser incluida en múltiples lugares sin mayor dificultad ni acoplamiento. Pero esa manera de pensar no es muy compatible con frameworks basados en acciones o requests, como es el caso de Rails (y muchos otros). Sí lo es en el caso de frameworks basados en componentes… en ellos efectivamente puedes definir esa unidad encapsulada de "lógica/vista" que puedes incluir sin mayor problema en cualquier lugar. La mayoría de los frameworks en el lado del cliente están siguiendo este modelo, aunque también los hay en el lado del servidor (Tapestry, JSF, ASP.NET Web forms). Pero a su vez éstos tienen otras desventajas…
