### ISSUE TITLE
Error potencial en la función runValidations de forms.js (de la aplicación Wican)

### ISSUE THREAD

**Issue by kburckin** [UC-IIC2513-2016-2/syllabus#10]
Intenté adaptar el código de forms.js, etc. de Wican para hacer las validaciones al lado cliente en nuestra aplicación. Sin embargo, mi formulario nunca pasó las validaciones para seguir con el 'Submit' normal (aunque todos los mensajes de errores desaparecieron). Eventualmente decidí probar esta funcionalidad en Wican sí mismo (en la página para crear un nuevo usuario: http://localhost:3000/users/new) y me parece que no funciona allá tampoco. No sé si estoy haciendo algo mal o si verdaderamente hay un error en el código.

Aquí es el código original de la función (https://github.com/UC-IIC2513-2016-2/wican/blob/develop/app/assets/javascripts/forms.js)

```
function runValidations($field) {
  clearErrors($field);
  var inputValidations = $field.data('validate') || {};
  if ($field.prop('required')) {
    inputValidations.required = true;
  }
  for (var validationName in inputValidations) {
    if (!runValidation($field, validationName, inputValidations[validationName])) {
      formHasErrors = true;
      break;
    }
  }
}
```

Yo leí que en JavaScript, una función sin "return" retorna el valor "undefined". Creo que esto está pasando cada vez que se corre la función porque no hay "return" en la función y como resultado el siguiente condicional siempre está verdadera (porque !undefined == true).

```
if (!runValidations($(this))) {
  formHasErrors = true;
}
```

Yo cambié el código un poquito para ver si arreglaría el problema y creo que funciona.
```
function runValidations($field) {
  clearErrors($field);
  var inputValidations = $field.data('validate') || {};
  if ($field.prop('required')) {
    inputValidations.required = true;
  }
  for (var validationName in inputValidations) {
    if (!runValidation($field, validationName, inputValidations[validationName])) {
      formHasErrors = true;
      return false; // CAMBIO AQUÍ
    }
  }
  return true; // CAMBIO AQUÍ
}
```

Quizás hay algo que no entiendo sobre JavaScript porque no sé porque el código pone el valor de la variable formHasErrors en la condicional en la función runValidations, pero nunca la usa. Tal vez queremos usarla para decidir lo que queremos retornar?

Me gustaría saber si verdaderamente hay un error en el código (y un cambio como el mío es necesario) or si solamente es algo que no entiendo o estoy haciendo mal. Gracias!

**Comment by raulmt** [comment]
Hola @kburckin . Tienes toda la razón, hay un error ahí. Me tinca que fue en algún movimiento de código, pues esa variable `formHasErrors` ni siquiera está declarada (y, de hecho, no sirve de nada… basta con los 2 returns que agregaste tú).

Gracias por encontrar el error y por resolverlo. Quieres crear un PR con este cambio y lo corregimos?

**Comment by raulmt** [comment]
solucionado aquí UC-IIC2513-2016-2/wican#1
