### ISSUE TITLE
REST o RESTful ?

### ISSUE THREAD

**Issue by TristanPouliquen** [UC-IIC2513-2016-2/syllabus#11]
Hola,

Sobre el enunciado de la entrega 6, como se evaluara que la API esta REST o no ? 

Hacer una API realmente REST es bastante complicado y necesita el respeto de varios puntos tal como especificar la localizacion, URLS para seguir el camino en la API, request stateless, self-descripting....

**Comment by raulmt** [comment]
Lo mínimo es que respeten que sea stateless (para lo que requiera autenticación pueden usar tokens) y que respeten dónde especifican la acción (método HTTP), scope (URL) y data (en body directamente, usualmente como JSON o XML) asociado a un request.

Agregar links es una buena práctica igual. Si usas _active model serializers_ que es lo que usamos en clases, puedes cambiar el adaptador a json_api, con lo que utilizarás la especificación [JSON API](http://jsonapi.org). Y ahi podrás más agregar de una manera estándar los links para hacer tus respuestas navegables.

**Comment by TristanPouliquen** [comment]
Ok gracias !
