### ISSUE TITLE
¿Alcanzaremos a tener la nota de la i3 antes del examen?

### ISSUE THREAD

**Issue by jgmontoya** [UC-IIC2513-2016-2/syllabus#13]
¿Se sabe más o menos cuándo estarán las notas?

Saludos!

**Comment by raulmt** [comment]
[Sí](https://docs.google.com/spreadsheets/d/1cZ9I9ExbjGCZ6lHNWGHAZRUonofZGjDrXGNDwuvAQHI/edit#gid=822069327).

**Comment by jgmontoya** [comment]
Gracias!
