### ISSUE TITLE
Serializers con asociaciones / pregunta sobre ong_serializer

### ISSUE THREAD

**Issue by kburckin** [UC-IIC2513-2016-2/syllabus#15]
Estoy corriendo la aplicación Wican sin modificaciones al código. Sin embargo, cuando voy a http://localhost:3000/api/v1/ongs no veo los títulos en el JSON de las iniciativas como según yo código indica (en línea 8 ahora mismo).

Código: wican/app/serializers/ong_serializer.rb (https://github.com/UC-IIC2513-2016-2/wican/blob/develop/app/serializers/ong_serializer.rb)

![image](https://cloud.githubusercontent.com/assets/7539225/20652982/7703715c-b4e3-11e6-94d0-fd505c1f0043.png)

¿Estoy haciendo/entendiendo algo incorrectamente? Me parece que no está usando el InitiativeSerializer.

Pregunto porque estoy teniendo problemas con construir mi API por la misma razón (de mostrar las asociaciones y sus atributos).

Gracias!

**Comment by kburckin** [comment]
Oops. Literalmente un minuto después de publicar este issue, pensé en otra posibilidad. No me había dado cuenta de que la información era en "included" en vez de "data". Acabo de encontrar los títulos :(  Lo siento por publicar!

**Comment by raulmt** [comment]
No, no lo sientas… cuando incluyes la respuesta igual sirve como Q&A ;)

Estos serializers se pueden configurar con diferentes formatos de respuesta JSON. Por ejemplo, puedes hacer que el JSON entregado sea directamente el objeto que representas, o que sea un objeto que tiene una propiedad que es el nombre de lo que estás incluyendo ("ong" en este ejemplo) y el valor de esa key será el objeto en cuestión… y la última, que es la que dejé configurada en wican, es la que genera automáticamente un JSON según la especificación [JSON API](http://jsonapi.org).

En ella las propiedades están dentro de este "data", y existe este atributo "relationships" que sólo tiene id/tipo de las relaciones (de manera que podrías ir a buscarlas según eso en algún otro request). Si específicamente pides que se incluyan los objetos de la entidad Initiative (lo cual está hecho [aquí](https://github.com/UC-IIC2513-2016-2/wican/blob/develop/app/controllers/api/v1/ongs_controller.rb#L7)) entonces los tendrás esos datos en ese otro atributo, "included".
