### ISSUE TITLE
Documentación del proyecto.

### ISSUE THREAD

**Issue by jgmontoya** [UC-IIC2513-2016-2/syllabus#17]
Hola, 

Quería saber si es posible entregar la parte de esta entrega correspondiente a la documentación más tarde (digamos mañana, por ejemplo) sin incurrir en penalizaciones por atraso :pray: 

Saludos!

**Comment by raulmt** [comment]
Hola Javier,

Ok, mañana a las 10pm como máximo (esto **sólo** para la documentación solicitada, no para el resto de los requisitos). No más que eso pues los ayudantes tienen que revisar esto antes del viernes.

Por favor no cierres el issue hasta mañana para que esté más visible ;)

**Comment by jgmontoya** [comment]
Excelente, gracias!
