### ISSUE TITLE
[Off topic] Información respecto al próximo semestre

### ISSUE THREAD

**Issue by jgmontoya** [UC-IIC2513-2016-2/syllabus#18]
Hola,

Quería saber si al final el próximo semestre el curso será en javascript o si seguirá siendo en rails.

También me gustaría saber si existe alguna posibilidad de convalidar el proyecto en caso de reprobar por nota de pruebas.

Saludos!

**Comment by raulmt** [comment]
Hola. Es una pregunta tempranamente pesimista, no? :(

El próximo semestre será en Rails por seguro. El subsiguiente es el que está en estudio.

Respecto a "convalidaciones", no existen a nivel de componente del curso. Para aprobar el curso en una instancia tienes que aprobar ambos componentes, teórico y práctico, en la instancia en que lo haces.

Saludos,
Raúl.

**Comment by jgmontoya** [comment]
Ah ok, gracias!

Última pregunta de esto, ¿Qué profesor hará el curso el próximo semestre?

**Comment by raulmt** [comment]
un profe nuevo (en el contexto de este curso), Rodrigo Saffie (actual profesor del curso de arquitectura de sistemas… o de nombre similar que no recuerdo exactamente).
