### ISSUE TITLE
Los datos de seed para producción

### ISSUE THREAD

**Issue by kburckin** [UC-IIC2513-2016-2/syllabus#3]
Ayer pregunté al profesor sobre este tema en clase, pero todavía estoy un poco confundida.

Nuestra aplicación necesita algunos datos en la base de datos para que funcione. Creo que este caso es distinto del caso de los seeds cuando están usados para probar/mostrar como funciona la aplicación.

El profesor me dijo que debemos usar una migración para insertar los datos. He leído en línea que es mejor usar "raw SQL" en vez de hacer las inserciones a través de Rails (en el caso en que el schema/modelo cambie) (http://stackoverflow.com/questions/2667580/how-do-i-add-some-inserts-in-rails-migration/2667747#2667747).

Sin embargo, también he encontrado otras páginas que dicen que debes usar el archivo de db/seeds.rb para insertar los datos (http://stackoverflow.com/questions/8662127/how-to-use-seed-rb-to-selectively-populate-development-and-or-production-databas).

Ahora estoy confundida con respeto a la manera correcta de hacerlo. Gracias por la ayuda.

**Comment by raulmt** [comment]
No hay una respuesta así como "oficialmente" correcta, hasta donde sé… lo que [dice Rails oficialmente](http://guides.rubyonrails.org/active_record_migrations.html#migrations-and-seed-data) esencialmente es lo que conversamos en clases, que son esas dos alternativas: migrations y seeds. Ninguna de ellas es estricta en cuanto a popular bases de datos. En este tema tienes, de hecho, múltiples opciones, cada una con ventajas y desventajas, y creo que es más bien decisión de cada equipo cuál usar dependiendo de cada caso:
- agregar datos en migraciones:
  - ventajas: sencillo, directo, tienes acceso a clases AR (ActiveRecord), puedes tener up/down, tienes una secuencia segura en cuanto a que una migración futura puede depender de la existencia de datos anteriores y además te aseguras que esos datos estarán presentes, pues no hay forma de evitar ejecutar migraciones cuando hay migraciones pendientes.
  - desventajas: las migraciones es algo que deberías evitar cambiarlas una vez que ya están publicadas… y si usas AR puede que la migración quede "obsoleta" y no sea ejecutable en el futuro si es que hay cambios importantes en AR. Una solución respecto a esto es lo que mencionas tú, usar raw SQL… pero ¿quién quiere escribir raw SQL? Así que en ese sentido quizá decidas usar AR y, si es que llegar a cambiar algo, alterar una migración anterior lo suficiente como para que siga funcionando (con mucho cuidado de no alterar el propósito de la misma y crear dos realidad paralelas que colapsarán el universo :O …).
- agregar datos en seed:
  - ventajas: igual de directo, sencillo, acceso a AR.
  - desventajas: esta características está más orientada, a mí parecer, a desarrollo, en donde hay una fuerte necesidad de tener datos de prueba de múltiples clases (no sólo datos básicos/estáticos como comunas, territorios electorales y cosas de ese estilo). Dado eso, probablemente necesitarías dejar datos tanto para desarrollo como para producción en ese mismo lugar, usando condiciones basadas en Rails.env para detectar en qué ambiente estás ejecutando ese seeds. Por otra parte, si AR cambia o migraciones alteran los atributos, por ejemplo, necesitas estar actualizando este archivo también.
- algo más manual… esencialmente algún otro archivo que se ejecute en el contexto de la aplicación y que cargue esos datos. Puede ser un simple archivo que ejecutas con `rails runner` o una [rake task](http://guides.rubyonrails.org/command_line.html#custom-rake-tasks). Creo que también existen algunas gemas que ayudan con algo como esto.
  - ventajas: tienes más menos lo mismo que en las dos anteriores, con la diferencia de que aquí sí puedes dejar aislada la ejecución preparada para producción.
  - desventajas: más manual, necesitas crear más cosas y, al igual que seeds, no se te garantiza la ejecución como parte estructural de la aplicación.

En este caso, cualquiera de estas opciones que elijas va a estar dentro de lo razonable y dentro de lo que puedes esperar en una aplicación Rails.

**Comment by kburckin** [comment]
Gracias por la explicación detallada!
