### ISSUE TITLE
Temario i2

### ISSUE THREAD

**Issue by jgmontoya** [UC-IIC2513-2016-2/syllabus#4]
Hola, 

¿Hay algún temario específico de qué entrará en la i2?

Saludos!

**Comment by raulmt** [comment]
Hola. Para todas las ies y examen, la regla es la misma: todos los temas que hemos visto hasta 1 semana antes de la fecha de la evaluación. Sí, esto significa que es acumulativo, pero a la vez siempre puedes esperar mayor foco en los temas que no hayan sido aún evaluados. Ejemplo: necesitas manejar Ruby y ActiveRecord para esta I2? Sí, probablemente necesitarás eso para poder responder preguntas completas, pero el foco será mayor en templates, HTML, CSS, controlador, sesión, etc.

Respecto a HTML y CSS, no voy a esperar que sean una referencia humana de esos estándares. Pero sí que sepan su sintaxis, funcionamiento y elementos básicos como los que hemos usado en el proyecto de ejemplo y que probablemente también deban usar en sus propios proyectos. En el caso de CSS, las slides mencionan temas importantes también que debieran tener claro, como: posicionamiento, display, box-model, especificidad, etc…
