### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by TristanPouliquen** [UC-IIC2513-2016-2/syllabus#5]
Hola, 

Quiero saber si podemos utilizar una gema como Ratyrate (https://github.com/wazery/ratyrate) para manejar los ratings :)

Gracias

**Comment by raulmt** [comment]
Hola Tristán,

Ok, pueden usarla. Sin embargo, éste es el tipo de cosas que podrían haber implementado ustedes con JS en la entrega 5. Si usan esta librería para ello, tendrán que encontrar otras cosas interesantes que hacer con JS (no debería ser un problema, está lleno de cosas interesantes que se pueden hacer… pero cumplo con la advertencia).

Saludos,
Raúl.

**Comment by TristanPouliquen** [comment]
Ya encontré unos tutoriales con puro CSS  tambien. Sé que no es tan complicado manejarlo solo pero esta gema me parece proponer unas funcionalidades ademas.

Gracias!
