### ISSUE TITLE
Acceso a atributos despues de un join

### ISSUE THREAD

**Issue by jjsotomayor** [UC-IIC2513-2016-2/syllabus#6]
Estoy tratando de hacer un join simple de 2 tablas, el comando que uso es como el siguiente:

`@relation = Category.joins(:category_type).where(category_types: {project_id: 1})`

donde Category y CategoryType son las 2 clases que se hacen join. 
La consulta me devuelve una relacion correcta, pero no logro acceder a los atributos que pertenecen a la tabla category_types.

Por ejemplo, para acceder a algo de Category puedo usar  `@relation.first.atributo`, pero no lo puedo hacer para un atributo de CategoryType. (Al parecer los atributos de CategoryType no quedan accesibles).

Hay algun comando especial para acceder a los atributos de la 2da tabla (CategoryType)? O es necesario hacer el join de otra manera?

Gracias!!

**Comment by raulmt** [comment]
Lo que hace `joins` es agregar, en la consulta final a ejecutar, un join con otra tabla con una cierta condición ("ON…"). Como le entregas un símbolo, se supone como una de las relaciones de Category y entonces ActiveRecord deduce la tabla con la cual hacer el join y además la condición. Si bien este join te deja disponibles los atributos de `category_types` en el resto de la consulta (como los estás usando en el `where` que tienes) no te modifica la sección del SELECT de la consulta ni mucho menos cómo se crean los objetos a luego a partir de los datos.

Como regla general, si tú usas el modelo ActiveRecord `Category`, siempre vas a obtener como resultado "categories", que sólo contendrán los atributos que corresponden a un `Category`.

Sin embargo, si estás usando ese join, probablemente category belongs_to category_type, ¿cierto? Si es así, entonces siempre puedes llegar a los atributos de category_type a través de la relación:

``` ruby
@relation.first # este es una instancia de Category
@relation.first.category_type.atributo_de_category_type
```

¿Te sirve eso? En términos prácticos, creo que debiera servirte. Ahora, sí hay un problema de eficiencia con ello. Y es que por cada Category a la cual accedas a su category_type, se tendrá que cargar ese category_type desde la BD con una consulta. Y quizá tu querías cargar "todo de una". Si ese es el caso te recomiendo [esta sección de los docs de Rails](http://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations).

**Comment by jjsotomayor** [comment]
Gracias profe! Si soluciona mi problema por ahora, aunque igual me quedan unas dudas de como usar joins cuando hay relaciones n-n (y por lo tanto tablas intermedias).
Pero por ahora ya logre solucionar lo que necesitaba de una manera no tan elegante, asi que prefiero preguntarle despues en clases para entenderlo mejor.
