### ISSUE TITLE
Problema deshabilitando CoffeeScript

### ISSUE THREAD

**Issue by fjval1** [UC-IIC2513-2016-2/syllabus#8]
Hola!
Tengo el siguiente problema: traté de deshabilitar coffeescript comentando la línea correspondiente en el gemfile, pero ahora me tira error cuando trato de abrir la app:

        <%= image_tag "logo.png",size: '250x200', id: "logo" %> --------------->esta línea es la que falla  

¿Qué hago?
Muchas gracias!

**Comment by raulmt** [comment]
Te puedo recomendar varias cosas relacionadas a tu pregunta:
- primero, que no preguntes "[tengo este error…] ¿Qué hago?", pues suena a que te enfrentas a un problema y dependes de que alguien te de instrucciones para resolverlo; esa no es una actitud deseable.
- segundo, que siempre que tengas un error en una aplicación, luego obviamente de buscar en Google y tratar de resolverlo por ustedes mismos, cuando preguntes en algún foro **siempre incluyas cuál es el error que estás viendo**. Muchas veces no basta con una descripción de lo que hiciste y con la línea en donde se te muestra que tienes un error (de hecho, cuando los errores se gatillan en el template, muchas veces no tienen que ver con el template en sí).
- tercero, a priori y sin saber qué error es el que estás viendo, lo que se me ocurre es que hayas eliminado la línea pero no hayas ejecutado un `bundle`, pero no suena muy probable. O que quizá lo hayas ejecutado, pero `spring` siga corriendo con una partida anterior del proceso. Para esto último tienes que detener el servidor y luego ejecutar `spring stop`, y luego partir el servidor de nuevo.

**Comment by fjval1** [comment]
Gracias, ya descubrí que era! Por si a alguien más le pasa, era que seguía teniendo archivos .coffee en la carpeta de javascript...no sé por qué esa línea en particular me tiraba error, pero borré los archivos y ahora funciona bien.
