### ISSUE TITLE
Cómo "linkear" archivos .js

### ISSUE THREAD

**Issue by fjval1** [UC-IIC2513-2016-2/syllabus#9]
Hola profe, tengo otra duda:

En 'wican' hay un archivo de nombre forms.js, ¿cómo se hace para que la app "sepa" que ese archivo está conectado a  _form.html.erb?  ¿Es por convención no más, o hay que especificarlo en algún lado?

Gracias!

**Comment by raulmt** [comment]
Lo que hemos visto en clases es que todos los archivos JS que tengas en tu aplicación se incluyen en el head del layout por default. Esto es porque hay una línea que incluye "application", y si miras el archivo application.js verás que tiene una línea que dice `require_tree`. Ésta línea es la que incluirá todos los archivos del directorio y subdirectorios.

En desarrollo verás todos estos archivos por separado, pero en producción (como cuando ves la app desde heroku) verás que todos estos archivos están concatenados en un único archivo (pues, en general, es más eficiente de esa manera).

Lo anterior significa que todo código JS que escribas siempre se ejecutará, no importa la página que cargues. Por eso es importante que el código que escribas tenga eso en consideración.

Por ejemplo, el archivo de wican que mencionas, `form.js`, busca todos los formularios de clase `validate` que encuentre. Si no encuentra ninguno (como ocurrirá en varias páginas) simplemente no se agregará ningún _listener_ al evento `submit`. Pero si tu código depende de encontrar un elemento en particular y, si no existe, entonces falla, tendrás problemas en todas las páginas que no tengan ese elemento en cuestión.

Otra opción que puedes considerar es utilizar [esas clases de controller y action](https://github.com/UC-IIC2513-2016-2/wican/blob/develop/app/views/layouts/application.html.erb#L11) que agregamos, en su momento, para CSS. También las puedes usar para detectar si cierto código quieres que se ejecute o no (por ejemplo, para ejecutar algo sólo si estamos en la acción X del controlador Y).

**Comment by fjval1** [comment]
Muchas gracias, me quedó claro!
